# TODO we REALLY would like to get caching to work properly

name: Kybra Property Tests
on:
    push:
        branches:
            - main
    pull_request: # Runs on pull requests to any branch
jobs:
    basic-integration-tests: # TODO let's change the name of this
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false # We want to see which example tests succeed and which ones fail, we don't want one example test to cancel the rest
            matrix:
                # TODO perhaps we should start testing on different versions of dfx as well
                rust: [stable]
                tests:
                    - name: test_text
                      directory: kybra_tests/src/candid_types/text
        steps:
            - uses: actions/checkout@v3
            - run: DFX_VERSION=0.12.0 sh -ci "$(curl -fsSL https://sdk.dfinity.org/install.sh)"
            - name: Install Rust ${{ matrix.rust }}
              uses: actions-rs/toolchain@v1
              with:
                  toolchain: ${{ matrix.rust }}
                  profile: minimal
                  override: true
            - run: curl https://pyenv.run | bash
            - run: ~/.pyenv/bin/pyenv install 3.10.7
            - working-directory: ${{ matrix.tests.directory }}
              run: dfx start --clean --background --host 127.0.0.1:8000
            - working-directory: kybra_tests
              shell: bash -l {0}
              run: KYBRA_CASES=10 cargo test -- --nocapture --test ${{ matrix.tests.name }} # TODO we will want to configure KYBRA_CASES based on release candidates and full releases etc
              # TODO we keep failing at No such file or directory (os error 2), maybe the main.py file is not being written correctly

    check-basic-integration-tests-success:
        needs: basic-integration-tests
        runs-on: ubuntu-latest
        if: success()
        steps:
            - run: exit 0

    check-basic-integration-tests-failure:
        needs: basic-integration-tests
        runs-on: ubuntu-latest
        if: failure()
        steps:
            - run: exit 1
